baseURL: ""
languageCode: "en-us"
languageName: "English"
title: "Toesmasher.se"
theme: LoveIt

paginate: 12
# googleAnalytics: G-DWJJVE27WD

markup:
  highlight:
    noClasses: false

permalinks:
  blog: :section/:year/:month/:title

author:
  name: "Niklas Berggren"
  email: nicke@toesmasher.se

menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    - identifier: projects
      name: Projects
      title: Projects
      url: /projects
      weight: 2

    - identifier: CV
      name: CV
      title: CV
      url: /CV
      weight: 3

params:
  defaultTheme: "dark"

  header:
    title:
      name: "Toesmasher.se"
      description: "The various things I do"
      logo: "/images/favicon_toesmasher.png"
      typeit: false

  search:
    enable: false

  footer:
    enable: true
    hugo: false
    copyright: true
    since: 2022
    author: true

  section:
    paginate: 20
    dateFormat: "01-02"
    rss: 20

  list:
    paginate: 20
    dateFormat: "XX-YY"
    rss: 20

  home:
    profile:
      enable: true
      avatarURL: "/images/toesmasher.jpg"
      title: "Niklas Berggren"
      subtitle: "Coding, Cooking, Tinkering and Playing"
      social: true 

  social:
    GitHub: "Toesmasher"
    LinkedIn: "niklas-berggren-a4339b19"
    Instagram: "berggren.niklas"
    Spotify: "6t1hwpqc5nxsbt8kk0tkuf5nl"
    Email: "nicke@toesmasher.se"

  page:
    toc:
      enable: true
      keepStatic: false
      auto: false

    code:
      copy: true

    comment:
      enable: false

