baseURL = 'https://www.toesmasher.se'
languageCode = 'en'
title = 'Toesmasher'

theme = 'hugo-coder'
paginate = 20

PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"

buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

[author]
  name = "Toesmasher"

[taxonomies]
  tag = "tags"
  category = "categories"
  project = "projects"

[permalinks]
  blog = "blog/:year/:month/:title"
  projects = "projects/:year/:month/:title"

[params]
  colorScheme = "auto"
  hideColorSchemeToggle = true
  dateFormat = "January 2, 2006"
  description = "The various things I do"
  info = "The various things I do"
  keywords = "Blog, BSD, Development, DM, Dungeons & Dragons, Embedded, FreeBSD, Linux, Unix"
  avatarURL = "images/Toesmasher.png"

[[languages.en.menu.main]]
  name = "CV"
  weight = 1
  url = "/cv"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url = "/blog"

[[languages.en.menu.main]]
  name = "Projects"
  weight = 3
  url = "/projects"

[[params.social]]
  name = "github"
  icon = "fa fa-2x fa-github"
  url = "https://github.com/toesmasher"

[[params.social]]
  name = "linkedin"
  icon = "fa fa-2x fa-linkedin"
  url = "https://www.linkedin.com/in/niklas-berggren-a4339b19"
