baseURL = 'https://toesmasher.se'
languageCode = 'en'
title = 'Toesmasher.se'
enableRobotsTXT = true

theme = "gokarna-hugo"
pygmentsStyle = "catppuccin-macchiato"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "CV"
    url = "/CV"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[params]
  avatarURL = "images/toesmasher.jpg"
  avatarAltText = "Drawn by an artistically inclined friend"
  avatarSize = "size-m"

  description = "Coding, cooking, tinkering and playing"
  metaKeywords = [ "blog", "coding" ]

  dateFormat = "2025-04-06 11:57"
  numberPostsOnHomePage = 4
  showBackToTopButton = true

  socialIcons = [
        { name = "github", url = "https://github.com/toesmasher" },
        { name = "linkedin", url = "https://linkedin.com/in/niklas-berggren-a4339b19" },
        { name = "spotify", url = "https://open.spotify.com/user/6t1hwpqc5nxsbt8kk0tkuf5nl" },
        { name = "email", url = "mailto:nicke@toesmasher.se" },
  ]
